### ISSUE TITLE
Incorrect Searching when using Ctrl or Shift to select tag combinations.

### ISSUE THREAD

**Issue by anmolnigam** [glfharris/echelon#1]
When using the browser, **ctrl** and **shift** can be used to quickly add tags to the current search criteria ([described here](https://apps.ankiweb.net/docs/manual.html#sidebar)).

However, the queries for selected hierarchical tags are not segmented. For example:
_"tag:Anatomy or tag:Anatomy::* or tag:Cardiovascular or tag:Cardiovascular::*"_

This could easily be fixed by wrapping the tags with parenthesis so that it reads as follows:
_"(tag:Anatomy or tag:Anatomy::*) or (tag:Cardiovascular or tag:Cardiovascular::*)"_

**Comment by glfharris** [comment]
Yeah, definitely a good idea. I'll add it for the next version. Thanks!

**Comment by glfharris** [comment]
Bit late, but fixed as of latest version
