### ISSUE TITLE
Addon interferes with 'Customize Sidebar' addon

### ISSUE THREAD

**Issue by Krakyn** [glfharris/echelon#11]
Love your addon! Two issues for you :) 

**1. Addon interferes with 'Customize Sidebar' addon**

View with just 'Customize Sidebar' enabled:

![image](https://user-images.githubusercontent.com/54581534/64001170-9e939000-cb4a-11e9-8b52-c66f094f8e6a.png)

See how my decks & note types are collapsed by default? (Customize Sidebar achieves this)

Now with 'Customize Sidebar' & Echelon enabled:

![image](https://user-images.githubusercontent.com/54581534/64001308-df8ba480-cb4a-11e9-9d91-91e65d29acf6.png)

See how all of my decks & note types have been expanded because of the Echelon _"default_depth": 0_ setting? If you could somehow change the behaviour of Echelon so that this interaction doesn't occur that would be great!

**2. Not really an issue, rather a suggestion, but can you add a lower default depth?**

 Currently _"default_depth": 0_ looks like this:

![image](https://user-images.githubusercontent.com/54581534/64001781-e49d2380-cb4b-11e9-968f-df9dc95f7f2e.png)

Can you change this/add an option so that !MD1_Blocks and !MD1_Lectures would be collapsed by default?

Cheers for your time and effort!

**Comment by glfharris** [comment]
Sorry this is so late, but this should be fixed in the latest version. Turns out it's a quirk of QT that 0 isn't fully closed.
New behavior: `default_depth` of 0 should now be completely collapsed
