### ISSUE TITLE
Problem on browsing

### ISSUE THREAD

**Issue by bagwell351** [glfharris/echelon#15]
When I am on the Panel Page and click on a Subtag (eg Tag1::SubTag1) in SideBar, the program looks for:
(tag::Tag1::SubTag1 or tag::Tag1::SubTag1::*)
and an error appears "Invalid search - please check for typos."
The search function only works using the menu: Filter -> Tag -> Click on the Tag1::SubTag1, then the program looks for:
"tag::Tag1::SubTag1"
and cards with SubTag1 appear.

I have some questions:
- Is it normal the search function not to work by clicking on SideBar?
- Can I edit the code so that clicking on the sidebar looks for the same term as when using the Filter option?

Sorry if I didn't make myself understood, English is not my first language.
Thank you very much in advance

Edit: Sorry for bothering. The problem occurred because the tags involved parentheses (eg Tag1(Edited)::SubTag1)

Solved

**Comment by glfharris** [comment]
Yeah, unfortunately I think parens in tag names is just going to cause problems with Anki's filtering.

I don't quite understand what you mean by the second question. Normally you can edit any text in the filter bar to fine tune the search

**Comment by bagwell351** [comment]
> Yeah, unfortunately I think parens in tag names is just going to cause problems with Anki's filtering.
> 
> I don't quite understand what you mean by the second question. Normally you can edit any text in the filter bar to fine tune the search

Initially I thought the problem was what the program looked for/typed into the search bar (as there was a difference in what appeared when I clicked on the tag, and when I searched using the menu), and my idea would be to edit the source code to change that. But the problem was all because of the use of parentheses. Everything's solved. Thanks anyway for the return.
