### ISSUE TITLE
doesn' work with the recently released 2.1.17

### ISSUE THREAD

**Issue by ijgnd** [glfharris/echelon#17]
the changelog for [2.1.17](https://apps.ankiweb.net/docs/changes.html) has 

> Add-ons that modify the sidebar will break when you update, and will need to be updated by the add-on author.

on your ankiweb description you recommend the add-on blitzkrieg which has a working unpublished version for 2.1.17 but average users can't install it. 

Glutanimate just released [Hierarchical Tags 2 (Anki 2.1.17 support)](https://ankiweb.net/shared/info/594329229) which is the only easy to install sidebar add-on at the moment/today.

I guess an update of the description is better than just a review.

Thanks for sharing all your add-ons, especially the syllabus add-on.

**Comment by glfharris** [comment]
Thanks for the heads up!
Yeah I'll update the description to link to those. Atm I'm leaving the ankiweb page up to link to the other add-ons as I'll probably not be updating this one unless there's suddenly a real need for another tags mod.
