### ISSUE TITLE
Addon hides internal Anki tags (e.g. : "leech", "marked")

### ISSUE THREAD

**Issue by Self-Perfection** [glfharris/echelon#2]
Here screenshot of tag list without addon:

![without addon](https://user-images.githubusercontent.com/3757038/48067652-d9a28c80-e1e1-11e8-9256-eabd2dc83980.png)
And here with addon enabled:
![addon enabled](https://user-images.githubusercontent.com/3757038/48067678-e7f0a880-e1e1-11e8-91fa-e0b37377f91c.png)

This is not expected behaviour for me and I consider it a bug.

Though I admit that this protects special tags from renaming which might cause confusion.

**Comment by glfharris** [comment]
Yeah, definitely a bug. I take a look soon. Thanks!

**Comment by glfharris** [comment]
Bit late, but fixed as of latest version
