### ISSUE TITLE
Show only nested tag, rather that whole tag

### ISSUE THREAD

**Issue by jj71code** [glfharris/echelon#5]
At present my tag sidebar tag tree looks something like...

A&P
___A&P::Cardiovascular
______A&P::Cardiovascular::Baroreceptors-and-chemoreceptors
______A&P::Cardiovascular::Cardiac-output
______A&P::Cardiovascular::etc-etc-etc
___A&P::Gastrointestinal
___A&P::etc-etc

Is it possible for the tag tree to display only the "sub section" of the name at that level of nesting.
Something like...

A&P
___Cardiovascular
______Baroreceptors-and-chemoreceptors
______Cardiac-output
______etc-etc-etc
___Gastrointestinal
___etc-etc

By displaying the full tag such as "A&P::Cardiovascular::Baroreceptors-and-chemoreceptors", your sidebar needs to be very wide when using the tag tree to navigate to cards for editing, etc.

Back in the 2.0.x version that this was ported from it had that feature. I'm not sure if updates prevent this from being the case, but it just looked a lot neater and was easier to navigate. If this can be done, or added in as a setting that can be toggled on/off, that would be most appreciated.

**Comment by glfharris** [comment]
Yeah, I agree, that looks much clearer. I'll put it on the to do list. Thanks!

**Comment by c0eos** [comment]
I've implemented this feature, as an optional parameter. Waiting to see if my pull request will be accepted.

**Comment by glfharris** [comment]
Yes, sorry! Started a new job, so had limited spare time. Will likely merge this weekend.

Thanks for the contribution!

**Comment by glfharris** [comment]
Included in latest version, thanks for the help!
