### ISSUE TITLE
Error when trying to rename a Tag with an umlaut.

### ISSUE THREAD

**Issue by FrauWolf** [glfharris/echelon#6]
I get an error message whenever I try to rename an existing tag that has an umlaut in it.
I mean of course it's stupid to add umlauts and I'm going to change that right away, just wanted to let you know, not sure if there's anything you can do.

**Debug info:**
Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14
Flags: frz=True ao=True sv=2
Add-ons possibly involved: Echelon - Improved Hierarchical Tags for Anki 21

Caught exception:
  File "/Users/XXX/Library/Application Support/Anki2/addons21/829533913/echelon.py", line 72, in <lambda>
    a_rename.triggered.connect(lambda x: renameAction(self, event))
  File "/Users/XXX/Library/Application Support/Anki2/addons21/829533913/echelon.py", line 82, in renameAction
    print(row)
<class 'UnicodeEncodeError'>: 'ascii' codec can't encode character '\xfc' in position 4: ordinal not in range(128)

**Thank you for looking into that!**

**Comment by glfharris** [comment]
Thanks for alerting me!
Should be a relatively simple fix, will add it for the next release.

**Comment by glfharris** [comment]
Sorry for the delay, but this has been fixed in the current release
