### ISSUE TITLE
expand by default

### ISSUE THREAD

**Issue by galantra** [glfharris/echelon#8]
Everytime I open the browser, my tag tree is by default collapsed. Is it possible to have it expanded when opening?
Also, It would be even more useful to have it only expand to a certain level, e. g. show Grandpa::Father but not show Grandpa::Father::Daughter and Grandpa::Father::Son

**Comment by glfharris** [comment]
Thanks for the issue.

Have put `default_depth` option in the config to allow for default expansion of the tag tree, feor the new release.
